name: build openwrt-arm64 docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Download Firmware
        run: |
          wget https://github.com/mslovecc/openwrt-armvirt-v22.03.6/releases/download/2024.01.26-0939/openwrt-armvirt-64-default-rootfs.tar.gz -O openwrt.tar.gz
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag mslovecc/openwrt-arm64:latest \
            --platform linux/arm64 .
